### ISSUE TITLE
<nav> parameters are not working

### ISSUE THREAD

**Issue by CentrixDE** [CentrixDE/sysadmin_toolbox#2]
<nav> parameters are probably not working. Its not using the complete width/height even if its set to 100%.

HTML:
```html
<body>
    <nav class="side-menu">
        <ul>
            <li class="item1 fa fa-home"><a class="menu_title">Home</a></li>
            <li class="item2 fa fa-gear"><a class="menu_title">Tools</a></li>
            <li class="item3 fa fa-comments-o"><a class="menu_title">Instructions</a></li>
            <li class="item4 fa fa-file"><a class="menu_title">Resources</a></li>
            <li class="item5 fa fa-info-circle"><a class="menu_title">Informations & Updates</a></li>
        </ul>
    </nav>

</body>
```

CSS:
```css
body {
    background-color: #f0f0f0;
    color: #303030;
    font-family: 'Open Sans', sans-serif;
    width: 100%;
    height: 100%;
}

* {
    font-family: 'Open Sans', sans-serif;
}

h1 h2 h3 h4 h5 h6 {
    font-family: 'Lato', sans-serif;
}

.menu_title {
    margin-left: 7px;
}

.menu_title::after {
    content: "\A";
    white-space: pre;
}

ul {
    list-style: none;
}

li {
    float: left;
    width: 100%;
}

.side-menu {
    width: 12%;
    height: 100%;
    background-color: #FF5500;
    margin: 0px;
    border: 0px;
    padding: 15px;
}
```
